CREATE TABLE PRODUCT(
  IDPRODUCT IDENTITY,
  ITEMCODE BIGINT UNIQUE NOT NULL,
  PRODUCT_DESCRIPTION VARCHAR,
  PRICE DOUBLE PRECISION,
  PRODUCT_STATE VARCHAR NOT NULL,
  CREATION_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CREATOR VARCHAR NOT NULL,
  CONSTRAINT PK_PRODUCT PRIMARY KEY (IDPRODUCT)
);

CREATE TABLE SUPPLIER(
  IDSUPPLIER IDENTITY,
  SUPPLIER_NAME VARCHAR NOT NULL,
  COUNTRY VARCHAR NOT NULL,
  CONSTRAINT PK_SUPPLIER PRIMARY KEY (IDSUPPLIER)
);

CREATE TABLE PRODUCT_SUPPLIER(
  PRODUCT_ID BIGINT,
  SUPPLIER_ID BIGINT,
  CONSTRAINT FK_PRODUCT_SUPPLIER FOREIGN KEY (PRODUCT_ID)
  REFERENCES PRODUCT(IDPRODUCT),
  CONSTRAINT FK_SUPPLIER_PRODUCT FOREIGN KEY (SUPPLIER_ID)
  REFERENCES SUPPLIER(IDSUPPLIER),
  CONSTRAINT PK_PRODUCT_SUPPLIER PRIMARY KEY (PRODUCT_ID, SUPPLIER_ID)
);

CREATE TABLE PRICE_REDUCTION(
  IDPRICEREDUCTION IDENTITY,
  STARTDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  ENDDATE TIMESTAMP WITHOUT TIME ZONE,
  PRODUCT_ID BIGINT,
  CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID)
  REFERENCES PRODUCT(IDPRODUCT),
  CONSTRAINT PK_PRICE_REDUCTION PRIMARY KEY (IDPRICEREDUCTION)
);
